#!/usr/bin/env bash

primary='{{colors.primary.default.hex}}'
hex=${primary#\#}

r=$((16#${hex:0:2}))
g=$((16#${hex:2:2}))
b=$((16#${hex:4:2}))
p_ansi=$(((r >= 128) * 1 + (g >= 128) * 2 + (b >= 128) * 4))

ORIG_PATH=$(echo "$PATH" | tr ":" "\n" | grep -v "$HOME/.local/bin" | tr "\n" ":")

exec env PATH="$ORIG_PATH" tty-clock -C "$p_ansi" -s -c -n "$@"
